name: Build Kafka Test Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    matrix:
      plugin: [filesystem, s3, gcs, azure]

    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout sources
      - uses: actions/checkout@v4

      # Setup Docker credentials
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Container image for the filesystem plugin
      - name: Build the container
        run: docker build --no-cache --build-arg VERSION=$(cat version) --build-arg PLUGIN=${PLUGIN} -t ghcr.io/scholzj/kafka-tiered-storage-oci:$(cat version)-${PLUGIN} .
        env:
          PLUGIN: ${{ matrix.plugin }}
      - name: Push the container
        run: docker push ghcr.io/scholzj/kafka-tiered-storage-oci:$(cat version)-${PLUGIN}
        env:
          PLUGIN: ${{ matrix.plugin }}